name: GitHub README Stats Updater

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy GitHub README Stats
        uses: telemetry-deck/action-readme-stats@v1.0.0
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Custom settings for cyberpunk cyberpunk profile
